### ISSUE TITLE
clean option set to true KO?

### ISSUE THREAD

**Issue by frenchvandal** [TencentCloud/cos-action#6]
嗨，大家好！
Sorry my Chinese skills are very basic so I will write this issue in English.

Here is my use case:

I write a blog with the well-known static site generator Hugo. My blog content is stored in a GitHub repository. Each time I push a commit with new content, a GitHub action triggers Hugo, which generates the new static files, then cos-action uploads the files to my COS bucket, bind to my domain name with Tencent Cloud CDN.

My GitHub deployment process looks like this:

```
name: Deploy Hugo on Tencent COS

on:
  push:
    branches: master

env:
  HUGO_VERSION: 0.78.2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: true

      - name: Download Hugo
        run: sudo wget -q https://github.com/gohugoio/hugo/releases/download/v${{ env.HUGO_VERSION }}/hugo_${{ env.HUGO_VERSION }}_Linux-64bit.deb

      - name: Install Hugo
        run: sudo dpkg -i hugo_${{ env.HUGO_VERSION }}_Linux-64bit.deb

      - name: Build Hugo
        run: hugo --cleanDestinationDir --enableGitInfo --gc --minify --disableKinds RSS

      - uses: TencentCloud/cos-action@master
        with:
          secret_id: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
          cos_bucket: ${{ secrets.COS_BUCKET }}
          cos_region: ${{ secrets.COS_REGION }}
          local_path: public
          remote_path: /
          clean: true 
```

Hugo command always generates the whole static site, so the cos-action re-uploads all the files at each build. It may not be the most efficient but this is no problem since Hugo generates the blog files with the very same name.

The `clean` option comes really handy: if I remove or rename a file in my blog content, I want the original file (the one deleted or the one with the old name) to be removed from my COS bucket. There is no need for me to keep unnecessary old files. The problem is: the `clean` option set to `true` does not seem to function properly, at least not as I expect it to work.

Let me illustrate with an example:

1. I add a new image `test.png` file to my Hugo blog. I commit the change and push it to Github:

![image](https://user-images.githubusercontent.com/42499534/99900107-36305180-2cae-11eb-9ba8-ca4e8409207e.png)

2. The GitHub action worked fine and the new generated files (37) including `test.png` were uploaded into my COS bucket:

![image](https://user-images.githubusercontent.com/42499534/99900387-7512d700-2caf-11eb-8eab-cbf0150152e9.png)

![image](https://user-images.githubusercontent.com/42499534/99900518-17cb5580-2cb0-11eb-8566-ecdc58158047.png)

3. Now I rename the `test.png` into `new_test.png`, commit the change, push it to GitHub and wait for the action to kick in. Hugo command does not generate `test.png`, but only the renamed file `new_test.png` (37 files uploaded again).

![image](https://user-images.githubusercontent.com/42499534/99900805-37637d80-2cb2-11eb-9928-0a3772a1b591.png)

![image](https://user-images.githubusercontent.com/42499534/99900757-bf955300-2cb1-11eb-8314-5dda4c694c97.png)

4. As you can see in my COS bucket, `new_test.png` was successfully uploaded to my COS bucket, but the cleaning I expected did not happen, the original  `test.png` is still there:

![image](https://user-images.githubusercontent.com/42499534/99900792-1dc23600-2cb2-11eb-9e1f-008b27cc2915.png)

5. Last test: I delete `new_test.png` from my repo, and I commit the change.

![image](https://user-images.githubusercontent.com/42499534/99900893-d2f4ee00-2cb2-11eb-9cc9-17364cae2277.png)

6. Hugo command will now generate 36 files instead of 37 files (no `new_test.png`):

![image](https://user-images.githubusercontent.com/42499534/99900909-0a639a80-2cb3-11eb-9034-f40d32ddd80e.png)

7. The expected behavior is that cos-action cleans `new_test.png` from the COS bucket. Unfortunately all the old files are still online in my bucket 😢 As you can see in the screenshot, the modification timestamp of each test file meets my previous build jobs with cos-action, so no cleaning happened.

![image](https://user-images.githubusercontent.com/42499534/99900970-72b27c00-2cb3-11eb-9acd-c9e8dfdb93f0.png)

**Conclusion**
Is this a real bug or am I misunderstanding how the `clean` option set to `true` should work? Is there a way for me to achieve what I need: automatically delete the files in my bucket that are not in the local path. For now, each time I make a change to my blog, I need to remove manually the old files from the bucket via my Tencent Cloud console.

Also I browsed through the `COSCMD` CLI tool documentation, it seems that there is no synchronization option between local path and bucket path, which would have been very convenient.

Thank you 谢谢

P.S. The very same tests performed with your competitor Google Cloud Platform actions worked just fine:

![image](https://user-images.githubusercontent.com/42499534/99901288-e05fa780-2cb5-11eb-9b82-dd4da59046c2.png)

![image](https://user-images.githubusercontent.com/42499534/99901248-7b0bb680-2cb5-11eb-9a35-165f70195838.png)
